spring:
  datasource:
    url: jdbc:h2:mem:marveldb
    driver-class-name: org.h2.Driver
    username: superuser
    password: root
  jpa:
    defer-datasource-initialization: true
    
  h2:
    console:
      enabled: true