DROP TABLE IF EXISTS COMICS;

CREATE TABLE COMICS(
	
	ID_COMICS INT AUTO_INCREMENT PRIMARY KEY,
	ID_CHARACTERER INT,
	RESOURCE_COMICS VARCHAR (350),
	NAME_COMICS VARCHAR (500)
);

DROP TABLE IF EXISTS EVENTS;

CREATE TABLE EVENTS(
	
	ID_EVENTS INT AUTO_INCREMENT PRIMARY KEY,
	ID_CHARACTERER INT,
	RESOURCE_EVENTS VARCHAR (350),
	NAME_EVENTS VARCHAR (500)
);

DROP TABLE IF EXISTS SERIES;

CREATE TABLE SERIES(
	
	ID_SERIES INT AUTO_INCREMENT PRIMARY KEY,
	ID_CHARACTERER INT,
	RESOURCE_SERIES VARCHAR (350),
	NAME_SERIES VARCHAR (500)
);

DROP TABLE IF EXISTS STORIES;

CREATE TABLE STORIES(
	
	ID_STORIES INT AUTO_INCREMENT PRIMARY KEY,
	ID_CHARACTERER INT,
	RESOURCE_STORIES VARCHAR (350),
	NAME_STORIES VARCHAR (500)
);

DROP TABLE IF EXISTS CHARACTERS;

CREATE TABLE CHARACTERS(
	
	ID INT AUTO_INCREMENT PRIMARY KEY,
	ID_CHARACTERER INT,
	ID_COMICS INT,
	ID_EVENTS INT,
	ID_SERIES INT,
	ID_STORIES INT,
	NAME_CHARACTER VARCHAR(500)
);

DROP TABLE IF EXISTS BITACORA_API_ACCESS;

CREATE TABLE BITACORA_API_ACCESS(
	
	ID_BITACORA INT AUTO_INCREMENT PRIMARY KEY,
	ID_CHARACTERER INT,
	DATE_ACCESS DATE 
);



